from pydantic import BaseModel, Field
from .enums import Tier


class InterviewQuestion(BaseModel):
    """
    A single tailored interview question with full context.
    Generated by the QuestionGenerator based on the candidate's
    profile, tier, and identified weak spots.
    """
    question: str                                   # The actual question to ask
    rationale: str                                  # Why this question was chosen
    dimension: str                                  # Which scoring dimension it probes
                                                    # e.g. "ownership", "achievement",
                                                    #      "technical_depth", "skill_gap"
    difficulty: str                                 # "easy" | "medium" | "hard"
    follow_up: str | None = None                    # Optional follow-up if answer is weak


class InterviewPlan(BaseModel):
    """
    The complete interview plan for a candidate.
    Output of the QuestionGenerator.
    Paired with TierClassification for a full candidate assessment package.
    """
    # Context
    candidate_name: str
    jd_title: str
    tier: Tier

    # Opening context for the interviewer
    interviewer_briefing: str                       # 2–3 sentence summary for the
                                                    # interviewer before the call

    # The questions
    questions: list[InterviewQuestion] = Field(
        default_factory=list,
        min_length=5,
        max_length=8,
    )

    # Closing guidance
    red_flags: list[str] = Field(default_factory=list)     # Things to watch out for
    green_flags: list[str] = Field(default_factory=list)   # Things that would confirm fit
    recommended_duration_minutes: int = 45                 # Suggested interview length